import enumimport routing
class AllowedHeightsFootprintKeyMaskBits(enum.IntFlags):
    SMALL_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_SMALL_HEIGHT
    TINY_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_TINY_HEIGHT
    LOW_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_LOW_HEIGHT
    MEDIUM_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_MEDIUM_HEIGHT
    FLOATING = routing.FOOTPRINT_KEY_REQUIRE_FLOATING
    LARGE_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_LARGE_HEIGHT

class WadingFootprintKeyMaskBits(enum.IntFlags):
    WADING_DEEP = routing.FOOTPRINT_KEY_REQUIRE_WADING_DEEP
    WADING_MEDIUM = routing.FOOTPRINT_KEY_REQUIRE_WADING_MEDIUM
    WADING_SHALLOW = routing.FOOTPRINT_KEY_REQUIRE_WADING_SHALLOW
    WADING_VERY_SHALLOW = routing.FOOTPRINT_KEY_REQUIRE_WADING_VERY_SHALLOW
